-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 12:10:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stube` DEFAULT CHARACTER SET utf8 ;
USE `Stube` ;

-- -----------------------------------------------------
-- Table `Stube`.`ListVideos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`ListVideos` (
  `idLlistVideos` INT NOT NULL,
  PRIMARY KEY (`idLlistVideos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`Video` (
  `idVideo` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `descriptionVideo` TEXT(600) NOT NULL,
  `titleVideo` VARCHAR(100) NOT NULL,
  `urlVideo` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ListVideos_idLlistVideos` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  UNIQUE INDEX `idVideo_UNIQUE` (`idVideo` ASC) VISIBLE,
  INDEX `fk_Video_ListVideos1_idx` (`ListVideos_idLlistVideos` ASC) VISIBLE,
  CONSTRAINT `fk_Video_ListVideos1`
    FOREIGN KEY (`ListVideos_idLlistVideos`)
    REFERENCES `Stube`.`ListVideos` (`idLlistVideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = Default
ROW_FORMAT = Default;


-- -----------------------------------------------------
-- Table `Stube`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`User` (
  `idNameUser` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL,
  `passwordUser` VARCHAR(10) NOT NULL,
  `mailUser` VARCHAR(20) NOT NULL,
  `ListVideos_idLlistVideos` INT NOT NULL,
  PRIMARY KEY (`idNameUser`),
  UNIQUE INDEX `NomUsuari_UNIQUE` (`idNameUser` ASC) VISIBLE,
  UNIQUE INDEX `mailUsuari_UNIQUE` (`mailUser` ASC) VISIBLE,
  INDEX `fk_User_ListVideos_idx` (`ListVideos_idLlistVideos` ASC) VISIBLE,
  CONSTRAINT `fk_User_ListVideos`
    FOREIGN KEY (`ListVideos_idLlistVideos`)
    REFERENCES `Stube`.`ListVideos` (`idLlistVideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
