-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 10:53:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Botiga_de_quadres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Botiga_de_quadres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Botiga_de_quadres` DEFAULT CHARACTER SET utf8 ;
USE `Botiga_de_quadres` ;

-- -----------------------------------------------------
-- Table `Botiga_de_quadres`.`Pintor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Botiga_de_quadres`.`Pintor` (
  `idPintor` INT NOT NULL,
  `nomPintor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPintor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Botiga_de_quadres`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Botiga_de_quadres`.`Clients` (
  `idClients` INT NOT NULL,
  `NomClient` VARCHAR(45) NOT NULL,
  `DniClient` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Botiga_de_quadres`.`RegistreVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Botiga_de_quadres`.`RegistreVenda` (
  `idRegistreVenda` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `preuVenda` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idRegistreVenda`),
  INDEX `fk_RegistreCompra_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_RegistreCompra_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `Botiga_de_quadres`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Botiga_de_quadres`.`Quadre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Botiga_de_quadres`.`Quadre` (
  `idQuadre` INT NOT NULL AUTO_INCREMENT,
  `Pintor_idPintor` INT NULL,
  `RegistreVenda_idRegistreCompra` INT NOT NULL,
  `preuQuadre` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idQuadre`),
  INDEX `fk_Quadres_Pintor1_idx` (`Pintor_idPintor` ASC) VISIBLE,
  INDEX `fk_Quadre_RegistreVenda1_idx` (`RegistreVenda_idRegistreCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Quadres_Pintor1`
    FOREIGN KEY (`Pintor_idPintor`)
    REFERENCES `Botiga_de_quadres`.`Pintor` (`idPintor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quadre_RegistreVenda1`
    FOREIGN KEY (`RegistreVenda_idRegistreCompra`)
    REFERENCES `Botiga_de_quadres`.`RegistreVenda` (`idRegistreVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
