-- MySQL Script generated by MySQL Workbench
-- Sun Apr 19 11:50:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Amazon` DEFAULT CHARACTER SET utf8 ;
USE `Amazon` ;

-- -----------------------------------------------------
-- Table `Amazon`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nomAutor` VARCHAR(45) NOT NULL,
  `addressAutor` VARCHAR(100) NOT NULL,
  `diversosLlibres` TINYINT NOT NULL COMMENT 'Valor Boleà on 0 és True (múltiples llibres) i qualsevol nombre Fals (llibre únic).',
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`LLibre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`LLibre` (
  `idllibre` INT NOT NULL,
  `titolllibre` VARCHAR(45) NOT NULL,
  `unitatsLlibre` INT UNSIGNED NOT NULL,
  `preuLlibre` DECIMAL(6,2) UNSIGNED NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idllibre`),
  INDEX `fk_LLibre_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_LLibre_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Amazon`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Usuari` (
  `idUsuari` INT NOT NULL AUTO_INCREMENT,
  `nomUsuari` VARCHAR(45) NOT NULL,
  `mailUsuari` VARCHAR(45) NOT NULL,
  `passwordUsuari` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `dataFactura` VARCHAR(45) NOT NULL,
  `totalFactura` DECIMAL(6,2) NOT NULL,
  `Usuari_idUsuari` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Usuari1_idx` (`Usuari_idUsuari` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Usuari1`
    FOREIGN KEY (`Usuari_idUsuari`)
    REFERENCES `Amazon`.`Usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Cataleg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Cataleg` (
  `idCataleg` INT NOT NULL,
  `LLibre_idllibre` INT NOT NULL,
  PRIMARY KEY (`idCataleg`),
  INDEX `fk_Cataleg_LLibre1_idx` (`LLibre_idllibre` ASC) VISIBLE,
  CONSTRAINT `fk_Cataleg_LLibre1`
    FOREIGN KEY (`LLibre_idllibre`)
    REFERENCES `Amazon`.`LLibre` (`idllibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`FacturaDetallProducte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`FacturaDetallProducte` (
  `LLibre_idllibre` INT NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  `titolLlibre` VARCHAR(45) NOT NULL,
  `preullibre` INT NOT NULL,
  `quantitat` INT NOT NULL,
  PRIMARY KEY (`LLibre_idllibre`, `Factura_idFactura`),
  INDEX `fk_LLibre_has_Factura_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  INDEX `fk_LLibre_has_Factura_LLibre1_idx` (`LLibre_idllibre` ASC) VISIBLE,
  CONSTRAINT `fk_LLibre_has_Factura_LLibre1`
    FOREIGN KEY (`LLibre_idllibre`)
    REFERENCES `Amazon`.`LLibre` (`idllibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LLibre_has_Factura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Amazon`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
