-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 12:25:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CulDampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CulDampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CulDampolla` DEFAULT CHARACTER SET utf8 ;
USE `CulDampolla` ;

-- -----------------------------------------------------
-- Table `CulDampolla`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Proveidor` (
  `idProveidor` INT NOT NULL AUTO_INCREMENT,
  `NomProveidor` VARCHAR(45) NOT NULL,
  `AddressProveidor` VARCHAR(45) NOT NULL,
  `CodiPostalProveidor` VARCHAR(10) NOT NULL,
  `CiutatProveidor` VARCHAR(20) NOT NULL,
  `PaisProveidor` VARCHAR(20) NOT NULL,
  `TelefonProveidor` VARCHAR(15) NOT NULL,
  `FaxProveidor` VARCHAR(15) NOT NULL,
  `NIFProveidor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idProveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Marques` (
  `idMarques` INT NOT NULL,
  `NomMarca` VARCHAR(45) NOT NULL,
  `Proveidor_idProveidor` INT NOT NULL,
  PRIMARY KEY (`idMarques`, `Proveidor_idProveidor`),
  INDEX `fk_Marques_Proveidor1_idx` (`Proveidor_idProveidor` ASC) VISIBLE,
  CONSTRAINT `fk_Marques_Proveidor1`
    FOREIGN KEY (`Proveidor_idProveidor`)
    REFERENCES `CulDampolla`.`Proveidor` (`idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Muntura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Muntura` (
  `idMuntura` INT NOT NULL COMMENT 'Opcions:\n\nF = Flotant\nP = Pasta\nM = Metàl.lica\n',
  `tipusMuntura` VARCHAR(1) NOT NULL COMMENT 'Valors possibles:\n\nF = flotant\nP = ',
  PRIMARY KEY (`idMuntura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Ulleres` (
  `idUlleres` INT NOT NULL,
  `MarcaUlleres` VARCHAR(45) NOT NULL,
  `PreuUlleres` DECIMAL(6,2) NOT NULL,
  `colorVidreDret` VARCHAR(45) NOT NULL,
  `colorVidreEsq` VARCHAR(45) NOT NULL,
  `graduacioVidreDret` INT NOT NULL,
  `graduacioVidreEsq` VARCHAR(45) NOT NULL,
  `Marques_idMarques` INT NOT NULL,
  `Marques_Proveidor_idProveidor` INT NOT NULL,
  `Muntura_idMuntura` INT NOT NULL,
  PRIMARY KEY (`idUlleres`, `Marques_idMarques`, `Marques_Proveidor_idProveidor`, `Muntura_idMuntura`),
  INDEX `fk_Ulleres_Marques1_idx` (`Marques_idMarques` ASC, `Marques_Proveidor_idProveidor` ASC) VISIBLE,
  INDEX `fk_Ulleres_Muntura1_idx` (`Muntura_idMuntura` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Marques1`
    FOREIGN KEY (`Marques_idMarques` , `Marques_Proveidor_idProveidor`)
    REFERENCES `CulDampolla`.`Marques` (`idMarques` , `Proveidor_idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Muntura1`
    FOREIGN KEY (`Muntura_idMuntura`)
    REFERENCES `CulDampolla`.`Muntura` (`idMuntura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Client` (
  `idClients` INT NOT NULL,
  `NomClient` VARCHAR(45) NOT NULL,
  `AddressClient` VARCHAR(45) NOT NULL,
  `TfClient` VARCHAR(15) NOT NULL,
  `MailClient` VARCHAR(45) NOT NULL,
  `DataRegistreClient` DATETIME NOT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Recomanacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Recomanacions` (
  `idRecomanacions` INT NOT NULL,
  `tipusRecomanacio` VARCHAR(45) NOT NULL,
  `Client_idClients` INT NOT NULL,
  PRIMARY KEY (`idRecomanacions`, `Client_idClients`),
  INDEX `fk_Recomanacions_Client1_idx` (`Client_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_Recomanacions_Client1`
    FOREIGN KEY (`Client_idClients`)
    REFERENCES `CulDampolla`.`Client` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`Empleats` (
  `idEmpleats` INT NOT NULL,
  `NomEmpleat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampolla`.`DetallVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampolla`.`DetallVenda` (
  `idVenda` INT NOT NULL,
  `preuVenda` INT NOT NULL,
  `dataVenda` DATETIME NOT NULL,
  `Ulleres_idUlleres` INT NOT NULL,
  `Ulleres_Marques_idMarques` INT NOT NULL,
  `Ulleres_Marques_Proveidor_idProveidor` INT NOT NULL,
  `Ulleres_Muntura_idMuntura` INT NOT NULL,
  `Client_idClients` INT NOT NULL,
  `Empleats_idEmpleats` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Ulleres_idUlleres`, `Ulleres_Marques_idMarques`, `Ulleres_Marques_Proveidor_idProveidor`, `Ulleres_Muntura_idMuntura`, `Client_idClients`, `Empleats_idEmpleats`),
  INDEX `fk_DetallVenda_Ulleres1_idx` (`Ulleres_idUlleres` ASC, `Ulleres_Marques_idMarques` ASC, `Ulleres_Marques_Proveidor_idProveidor` ASC, `Ulleres_Muntura_idMuntura` ASC) VISIBLE,
  INDEX `fk_DetallVenda_Client1_idx` (`Client_idClients` ASC) VISIBLE,
  INDEX `fk_DetallVenda_Empleats1_idx` (`Empleats_idEmpleats` ASC) VISIBLE,
  CONSTRAINT `fk_DetallVenda_Ulleres1`
    FOREIGN KEY (`Ulleres_idUlleres` , `Ulleres_Marques_idMarques` , `Ulleres_Marques_Proveidor_idProveidor` , `Ulleres_Muntura_idMuntura`)
    REFERENCES `CulDampolla`.`Ulleres` (`idUlleres` , `Marques_idMarques` , `Marques_Proveidor_idProveidor` , `Muntura_idMuntura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallVenda_Client1`
    FOREIGN KEY (`Client_idClients`)
    REFERENCES `CulDampolla`.`Client` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallVenda_Empleats1`
    FOREIGN KEY (`Empleats_idEmpleats`)
    REFERENCES `CulDampolla`.`Empleats` (`idEmpleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
