-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 09:10:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema XarxaSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema XarxaSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `XarxaSocial` DEFAULT CHARACTER SET utf8 ;
USE `XarxaSocial` ;

-- -----------------------------------------------------
-- Table `XarxaSocial`.`Usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XarxaSocial`.`Usuaris` (
  `idUsuaris` INT NOT NULL,
  `NomUsuari` VARCHAR(45) NOT NULL,
  `MailUsuari` VARCHAR(45) NOT NULL,
  `ContrasenyaUsuari` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuaris`),
  UNIQUE INDEX `idUsuaris_UNIQUE` (`idUsuaris` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XarxaSocial`.`Amics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XarxaSocial`.`Amics` (
  `idAmics` INT NOT NULL,
  PRIMARY KEY (`idAmics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XarxaSocial`.`Fotografies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XarxaSocial`.`Fotografies` (
  `idFotografies` INT NOT NULL,
  `URLFotografia` VARCHAR(100) NOT NULL,
  `LlocFotografia` VARCHAR(45) NOT NULL,
  `Usuaris_idUsuaris` INT NOT NULL,
  PRIMARY KEY (`idFotografies`),
  INDEX `fk_Fotografies_Usuaris1_idx` (`Usuaris_idUsuaris` ASC) VISIBLE,
  UNIQUE INDEX `idFotografies_UNIQUE` (`idFotografies` ASC) VISIBLE,
  CONSTRAINT `fk_Fotografies_Usuaris1`
    FOREIGN KEY (`Usuaris_idUsuaris`)
    REFERENCES `XarxaSocial`.`Usuaris` (`idUsuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `XarxaSocial`.`Relacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XarxaSocial`.`Relacions` (
  `Usuaris_idUsuaris` INT NOT NULL,
  `Amistats_idAmistats` INT NOT NULL,
  `TipusIniciAmistat` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuaris_idUsuaris`, `Amistats_idAmistats`),
  INDEX `fk_Usuaris_has_Amistats_Amistats1_idx` (`Amistats_idAmistats` ASC) VISIBLE,
  INDEX `fk_Usuaris_has_Amistats_Usuaris_idx` (`Usuaris_idUsuaris` ASC) VISIBLE,
  CONSTRAINT `fk_Usuaris_has_Amistats_Usuaris`
    FOREIGN KEY (`Usuaris_idUsuaris`)
    REFERENCES `XarxaSocial`.`Usuaris` (`idUsuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuaris_has_Amistats_Amistats1`
    FOREIGN KEY (`Amistats_idAmistats`)
    REFERENCES `XarxaSocial`.`Amics` (`idAmics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
